var sfrequest = context.getVariable("saml.request");
var sf_decoded_request = context.getVariable("sf.decoded.request");
var sf_callback = context.getVariable("sf.callback");
var sfresponse = context.getVariable("response.content");

var encodedResponse = encodeBase64(sfresponse);

var html = '<html><head></head> <body> 1. Request received from Salesforce : <br><div><textarea style="width: 50%; height: 30%">' +  sf_decoded_request + '</textarea></div><br> 2. You would enter your login and password on Apigee (IDP). This step is skipped in this example. This example assumes successful login with Apigee (IDP)<br><form id="form1" method="post" action="' + sf_callback + '" enctype="application/x-www-form-urlencoded"> <div> <input name="SAMLResponse" type="hidden" rows="20" value="'
+ encodedResponse + '"/> </div> <div><br>3. SAML Response generated by Apigee (IDP) <br><textarea style="width: 50%; height: 30%">' +  sfresponse + '</textarea></div> <div><br><b> Click submit to send the encoded version of the SAML response above to Salesforce (SP). <input type="submit" value="Submit" /> </b></div> </form> </body> </html>';

context.setVariable("response.content", html);
context.setVariable("response.header.Content-Type", "text/html");

